# Generated by Django 6.0.2 on 2026-08-06 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('seeds', 'Seeds Catalog'), ('inventory', 'Inventory & Stock'), ('sales', 'Sales & Invoices'), ('purchases', 'Purchases & Bills'), ('gatepass', 'Gate Pass'), ('expenses', 'Expenses'), ('finance', 'Finance & Ledger'), ('reports', 'Reports'), ('settings', 'Settings'), ('accounts', 'User Management')], max_length=50)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
