# Generated by Django 6.0.2 on 2026-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_seed',
            field=models.BooleanField(default=True, verbose_name='Can Access Seed Management'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_trading',
            field=models.BooleanField(default=True, verbose_name='Can Access Trading Management'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('seeds', 'Seeds Catalog'), ('inventory', 'Inventory & Stock'), ('sales', 'Sales & Invoices'), ('purchases', 'Purchases & Bills'), ('gatepass', 'Gate Pass'), ('expenses', 'Expenses'), ('finance', 'Finance & Ledger'), ('reports', 'Reports'), ('settings', 'Settings'), ('accounts', 'User Management'), ('trading', 'Trading Management')], max_length=50),
        ),
    ]
