# Generated by Django 6.0.2 on 2026-08-21 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Account Name')),
                ('broker_name', models.CharField(max_length=150, verbose_name='Broker / Exchange Name')),
                ('account_number', models.CharField(max_length=100, verbose_name='Account ID / Number')),
                ('account_type', models.CharField(choices=[('Standard', 'Standard Account'), ('ECN', 'ECN Account'), ('VIP', 'VIP Account'), ('Demo', 'Demo Account'), ('Prop Firm', 'Prop Firm / Funded Account'), ('Crypto Spot', 'Crypto Spot'), ('Futures', 'Futures / Derivatives'), ('Other', 'Other Account Type')], default='Standard', max_length=50)),
                ('platform', models.CharField(choices=[('MetaTrader 4', 'MetaTrader 4 (MT4)'), ('MetaTrader 5', 'MetaTrader 5 (MT5)'), ('Binance', 'Binance'), ('Bybit', 'Bybit'), ('cTrader', 'cTrader'), ('TradingView', 'TradingView'), ('Other', 'Other Platform')], default='MetaTrader 5', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('current_equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('is_active', models.BooleanField(default=True, verbose_name='Account Active')),
                ('opening_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('symbol', models.CharField(help_text='e.g. EURUSD, XAUUSD, BTCUSDT, US30', max_length=50)),
                ('market_type', models.CharField(choices=[('Forex', 'Forex'), ('Crypto', 'Crypto'), ('Gold', 'Gold & Metals'), ('Indices', 'Indices'), ('Stocks', 'Stocks'), ('Commodities', 'Commodities'), ('Other', 'Other')], default='Forex', max_length=50)),
                ('direction', models.CharField(choices=[('Buy', 'Buy / Long'), ('Sell', 'Sell / Short')], default='Buy', max_length=10)),
                ('lot_size', models.DecimalField(decimal_places=4, default=0.01, max_digits=10, verbose_name='Lot Size / Quantity')),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=14)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('open_time', models.DateTimeField(blank=True, null=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('swap_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Gross Profit / Loss')),
                ('status', models.CharField(choices=[('Open', 'Open Trade'), ('Closed', 'Closed Trade')], default='Closed', max_length=20)),
                ('strategy', models.CharField(blank=True, help_text='e.g. Trend Following, Scalping, SMC, Breakout', max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-trade_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_method', models.CharField(default='Bank Wire', help_text='e.g. Bank Wire, USDT, Crypto, Card', max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Transaction / Ref ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ['-deposit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_method', models.CharField(default='Bank Wire', max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Transaction / Ref ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='trading.tradingaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-withdrawal_date', '-id'],
            },
        ),
    ]
