# Generated by Django 6.0.2 on 2026-08-21 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('pass_type', models.CharField(choices=[('Inward', 'Inward (Receipt)'), ('Outward', 'Outward (Dispatch)')], default='Inward', max_length=20)),
                ('date', models.DateField()),
                ('vehicle_no', models.CharField(max_length=50, verbose_name='Vehicle / Truck No.')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('party_name', models.CharField(max_length=150, verbose_name='Party / Customer / Supplier Name')),
                ('seed_item', models.CharField(max_length=150, verbose_name='Seed Variety / Lot Description')),
                ('bags_qty', models.IntegerField(default=0, verbose_name='Number of Bags')),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gross Weight (KG)')),
                ('tare_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tare Weight (KG)')),
                ('net_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Net Weight (KG)')),
                ('status', models.CharField(choices=[('Pending', 'Pending Inspection'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradingPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('supplier_name', models.CharField(max_length=150, verbose_name='Supplier / Grower Party Name')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Amount (PKR)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Paid Amount (PKR)')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance Amount (PKR)')),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradingPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(max_length=150, verbose_name='Seed Variety / Item')),
                ('bags_qty', models.IntegerField(default=1, verbose_name='Quantity / Bags')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Weight (KG / Maunds)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Rate (PKR)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Subtotal (PKR)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.tradingpurchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='TradingSalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=150, verbose_name='Customer / Buyer Party Name')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Amount (PKR)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Paid Amount (PKR)')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance Amount (PKR)')),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradingSalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(max_length=150, verbose_name='Seed Variety / Item')),
                ('bags_qty', models.IntegerField(default=1, verbose_name='Quantity / Bags')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Weight (KG / Maunds)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Rate (PKR)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Subtotal (PKR)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.tradingsalesinvoice')),
            ],
        ),
    ]
