# Generated by Django 6.0.2 on 2026-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_tradinggatepass_tradingpurchaseinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpurchaseinvoice',
            name='crop_name',
            field=models.CharField(blank=True, default='Wheat / Agricultural Crop', max_length=150, null=True, verbose_name='Crop Name'),
        ),
        migrations.AddField(
            model_name='tradingpurchaseinvoice',
            name='crop_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Crop Weight (Kg)'),
        ),
        migrations.AddField(
            model_name='tradingpurchaseinvoice',
            name='rate_per_40kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rate per 40 Kg (Maund) (PKR)'),
        ),
        migrations.AddField(
            model_name='tradingpurchaseitem',
            name='crop_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Crop Name'),
        ),
        migrations.AddField(
            model_name='tradingpurchaseitem',
            name='crop_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Crop Weight (Kg)'),
        ),
        migrations.AddField(
            model_name='tradingpurchaseitem',
            name='rate_per_40kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rate per 40 Kg (PKR)'),
        ),
        migrations.AddField(
            model_name='tradingsalesinvoice',
            name='crop_name',
            field=models.CharField(blank=True, default='Wheat / Agricultural Crop', max_length=150, null=True, verbose_name='Crop Name'),
        ),
        migrations.AddField(
            model_name='tradingsalesinvoice',
            name='crop_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Crop Weight (Kg)'),
        ),
        migrations.AddField(
            model_name='tradingsalesinvoice',
            name='rate_per_40kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rate per 40 Kg (Maund) (PKR)'),
        ),
        migrations.AddField(
            model_name='tradingsalesitem',
            name='crop_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Crop Name'),
        ),
        migrations.AddField(
            model_name='tradingsalesitem',
            name='crop_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Crop Weight (Kg)'),
        ),
        migrations.AddField(
            model_name='tradingsalesitem',
            name='rate_per_40kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rate per 40 Kg (PKR)'),
        ),
        migrations.AlterField(
            model_name='tradingpurchaseitem',
            name='seed_name',
            field=models.CharField(max_length=150, verbose_name='Seed / Crop Variety'),
        ),
        migrations.AlterField(
            model_name='tradingpurchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unit Rate (PKR)'),
        ),
        migrations.AlterField(
            model_name='tradingpurchaseitem',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Weight (KG)'),
        ),
        migrations.AlterField(
            model_name='tradingsalesitem',
            name='seed_name',
            field=models.CharField(max_length=150, verbose_name='Seed / Crop Variety'),
        ),
        migrations.AlterField(
            model_name='tradingsalesitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unit Rate (PKR)'),
        ),
        migrations.AlterField(
            model_name='tradingsalesitem',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Weight (KG)'),
        ),
    ]
