# Generated by Django 6.0.2 on 2026-08-21 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceDraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PURCHASE_INVOICE', 'Purchase Invoice'), ('SALES_INVOICE', 'Sales Invoice'), ('GATE_PASS', 'Gate Pass'), ('TRADING_SALES', 'Seeds Trading Sales Invoice'), ('TRADING_PURCHASE', 'Seeds Trading Purchase Invoice'), ('TRADING_GATEPASS', 'Seeds Trading Gate Pass')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT_PENDING', 'Draft Pending Approval'), ('APPROVED', 'Approved & Saved'), ('CANCELLED', 'Cancelled')], default='DRAFT_PENDING', max_length=20)),
                ('draft_data', models.JSONField(default=dict, help_text='Structured draft metadata and line items')),
                ('transcript_history', models.JSONField(default=list, help_text='Chronological conversation transcript')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_draft_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
