# Generated by Django 6.0.2 on 2026-08-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('variety', models.CharField(max_length=100)),
                ('packing_size', models.CharField(help_text='e.g. 10 Kg Bag, 50 Kg Bag, 1 Kg Pack', max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='Unit Weight (Kg)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='GST (%)')),
                ('min_stock_alert', models.IntegerField(default=10, verbose_name='Minimum Stock Alert Quantity')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/seeds/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seeds/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Discontinued', 'Discontinued'), ('Out of Stock', 'Out of Stock')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeds', to='seeds.brand')),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeds', to='seeds.croptype')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeds', to='seeds.seedcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SeedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('lot_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('initial_qty', models.IntegerField(default=0)),
                ('current_qty', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='seeds.seed')),
            ],
            options={
                'ordering': ['expiry_date'],
                'unique_together': {('batch_number', 'seed')},
            },
        ),
    ]
