# Generated by Django 6.0.2 on 2026-08-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AgriSeed Enterprise ERP', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Quality Seeds for Maximum Yield', max_length=255)),
                ('ntn', models.CharField(blank=True, max_length=50, null=True, verbose_name='NTN Number')),
                ('strn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sales Tax Reg No (STRN)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('invoice_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('phone', models.CharField(default='+92-42-111-222-333', max_length=30)),
                ('mobile', models.CharField(default='+92-300-1234567', max_length=30)),
                ('email', models.EmailField(default='info@agriseederp.com', max_length=254)),
                ('website', models.URLField(blank=True, default='https://agriseederp.com')),
                ('address', models.TextField(default='Industrial Agriculture Zone, Multan Road, Lahore, Pakistan')),
                ('city', models.CharField(default='Lahore', max_length=100)),
                ('currency_symbol', models.CharField(default='PKR', max_length=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='GST Rate (%)')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('purchase_prefix', models.CharField(default='PUR-', max_length=10)),
                ('gatepass_prefix', models.CharField(default='GP-', max_length=10)),
                ('invoice_footer', models.TextField(default='Thank you for your business! Quality Seed Certified by FSC&RD.')),
            ],
        ),
    ]
