# Generated by Django 6.0.2 on 2026-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(blank=True, default='https://agriseederp.com', max_length=255, null=True),
        ),
    ]
