# Generated by Django 6.0.2 on 2026-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_companyprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, default='Industrial Agriculture Zone, Multan Road, Lahore, Pakistan', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, default='Lahore', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='currency_symbol',
            field=models.CharField(blank=True, default='PKR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, default='info@agriseederp.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='gatepass_prefix',
            field=models.CharField(blank=True, default='GP-', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=18.0, max_digits=5, null=True, verbose_name='GST Rate (%)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='invoice_footer',
            field=models.TextField(blank=True, default='Thank you for your business! Quality Seed Certified by FSC&RD.', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV-', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='mobile',
            field=models.CharField(blank=True, default='+92-300-1234567', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, default='+92-42-111-222-333', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='purchase_prefix',
            field=models.CharField(blank=True, default='PUR-', max_length=10, null=True),
        ),
    ]
