# Generated by Django 6.0.2 on 2026-08-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_alter_companyprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='erp_base_url',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000', help_text="Used in QR codes so phones can open invoice verification pages. On local network use your PC's IP e.g. http://192.168.1.100:8000", max_length=255, null=True, verbose_name='ERP Server Base URL'),
        ),
    ]
