# Generated by Django 6.0.2 on 2026-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_companyprofile_erp_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='erp_base_url',
            field=models.CharField(blank=True, default='https://nowsheraseed.onrender.com', help_text='Used in QR codes so phones can open invoice verification pages.', max_length=255, null=True, verbose_name='ERP Server Base URL'),
        ),
    ]
