# Generated by Django 6.0.2 on 2026-08-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('DAMAGE', 'Damage Write-Off'), ('EXPIRED', 'Expiry Write-Off'), ('DEDUCTION', 'Manual Deduction / Correction')], max_length=20),
        ),
    ]
