# Generated by Django 6.0.2 on 2026-08-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('pass_type', models.CharField(choices=[('IN', 'Gate Pass IN (Inward Cargo)'), ('OUT', 'Gate Pass OUT (Outward Cargo)')], default='OUT', max_length=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('vehicle_number', models.CharField(help_text='e.g. LES-1234', max_length=50)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_cnic', models.CharField(max_length=20, verbose_name='Driver CNIC')),
                ('driver_mobile', models.CharField(max_length=30)),
                ('transport_company', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_reference', models.CharField(blank=True, help_text='Sales/Purchase Invoice #', max_length=100, null=True)),
                ('total_bags', models.PositiveIntegerField(default=0)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Weight (Kg)')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/gatepass/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Verified', 'Security Verified'), ('Completed', 'Completed / Dispatched')], default='Issued', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_gatepasses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
