# Generated by Django 6.0.2 on 2026-08-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='driver_cnic',
            field=models.CharField(max_length=20, verbose_name='Driver CNIC (XXXXX-XXXXXXX-X)'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='driver_mobile',
            field=models.CharField(max_length=30, verbose_name='Driver Mobile (03XXXXXXXXX)'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='pass_type',
            field=models.CharField(choices=[('SALES', 'Sales Outward Gate Pass (INV)'), ('PURCHASE', 'Purchase Inward Gate Pass (PUR)'), ('MANUAL', 'Manual / General Cargo Gate Pass')], default='SALES', max_length=15),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(blank=True, choices=[('Issued', 'Issued'), ('Verified', 'Security Verified'), ('Completed', 'Completed / Dispatched')], default='Issued', max_length=20),
        ),
    ]
