# Generated by Django 6.0.2 on 2026-08-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_alter_gatepass_driver_cnic_and_more'),
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional: Direct batch for manual inward pass', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='seeds.seedbatch'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='is_stock_updated',
            field=models.BooleanField(default=False, help_text='True if inward goods have been added to inventory stock'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='seed',
            field=models.ForeignKey(blank=True, help_text='Optional: Direct seed for manual inward pass', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='seeds.seed'),
        ),
    ]
