# Generated by Django 6.0.2 on 2026-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_gatepass_batch_gatepass_is_stock_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='is_stock_updated',
            field=models.BooleanField(blank=True, default=False, help_text='True if inward goods have been added to inventory stock'),
        ),
    ]
